//VideoUpload Actions
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const TAGS_ADD = 'TAGS_ADD';
export const TAGS_REMOVE = 'TAGS_REMOVE';
export const VIDEO_FILE_CHANGE = 'VIDEO_FILE_CHANGE';

export const CLEAR_URL = 'CLEAR_URL';
export const ADD_THUMBNAIL = 'ADD_THUMBNAIL';
export const ADD_CREDIT = 'ADD_CREDIT';
export const REMOVE_CREDIT = 'REMOVE_CREDIT';
export const CREDIT_HANDLE_CHANGE = 'CREDIT_HANDLE_CHANGE';

export const ALBUM_THUMBNAIL_ADD = 'ALBUM_THUMBNAIL_ADD';
export const ALBUM_THUMBNAIL_REMOVE = 'ALBUM_THUMBNAIL_REMOVE';

export const ADD_AUDIO_TRACKS = 'ADD_AUDIO_TRACKS';
export const REMOVE_AUDIO_TRACK = 'REMOVE_AUDIO_TRACK';
export const UPDATE_AUDIO_TRACK = 'UPDATE_AUDIO_TRACK';
export const UPDATE_AUDIO_TRACK_PRICE = 'UPDATE_AUDIO_TRACK_PRICE';

export const ADD_IMAGES = 'ADD_IMAGES';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const ADD_IMAGE_DETAIL = 'ADD_IMAGE_DETAIL';

export const UPDATE_DATA = 'UPDATE_DATA';

export const CLEAR_VIDEO_STATE = 'CLEAR_VIDEO_STATE';

export const PATH = 'PATH';
export const VIDEO_EDIT = 'VIDEO_EDIT';

export const PROFILE_USER = 'PROFILE_USER';
export const PROFILE_FEATURED_VIDEO = 'PROFILE_FEATURED_VIDEO';
export const PROFILLE_FEATURED_IMAGES = 'PROFILLE_FEATURED_IMAGES';
export const PROFILLE_FEATURED_AUDIOS = 'PROFILLE_FEATURED_AUDIOS';
export const PROFILE_SUBSCRIPTION_CHANGE = 'PROFILE_SUBSCRIPTION_CHANGE';
export const PROFILE_CLEAN = 'PROFILE_CLEAN';
export const PAYMENT_STATUS = 'PAYMENT_STATUS';
export const PLAN_DURATION_CHANGE = 'PLAN_DURATION_CHANGE';

export const ADS_CHIP_ADD = 'ADS_CHIP_ADD';
export const ADS_CHIP_REMOVE = 'ADS_CHIP_REMOVE';
export const ADS_AGE_CHANGE = 'ADS_AGE_CHANGE';
export const ADS_INPUT_CHANGE = 'ADS_INPUT_CHANGE';

export const GENRE_ADD = 'GENRE_ADD';
export const GENRE_REMOVE = 'GENRE_REMOVE';

export const FILTER_CHANGE = 'FILTER_CHANGE';
export const FILTER_RESET = 'FILTER_RESET';
export const FILTER_DATE = 'FILTER_DATE';

export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const REMOVE_SUBSCRIPTION = 'REMOVE_SUBSCRIPTION';
export const HANDLE_SUBSCRIPTION_CHANGE = 'HANDLE_SUBSCRIPTION_CHANGE';
export const HANDLE_SUBSCRIPTION_EDIT = 'HANDLE_SUBSCRIPTION_EDIT';

// Upload
export const SELECTED_PLANS_CHANGE = 'SELECTED_PLANS_CHANGE';

export const SUBHEADER_CHANGE = 'SUBHEADER_CHANGE';

export const SEARCH_RESULT = 'SEARCH_RESULT';
