export const terms = {
    title: 'Terms & Conditions',
    desc: `<h4>Last Updated: August 26th,2018</h4><p>Welcome to ArtBot! We are happy you have decided to use our products and services (“Services”). These Services are provided by ArtBot, LLC (“Artbot”, residing at Carmel, Indiana). You agree to follow this Terms of Service by using our Services. Please read carefully. Our Services include video and audio monetization and community collaboration through https://ArtBot.tv, related domains, and mobile applications.</p><p>1. Who May Use the ArtBot Service
AGE REQUIREMENT: You must be at least 13 years old to use the ArtBot Service.If you are at least 13, but are still a minor(this depends on where you live), you must have your parent or legal guardian's permission to use the ArtBot Service. Please have him or her read this Agreement with you.</p><p>NOTICE TO PARENTS AND GUARDIANS: By granting your child permission to use the ArtBot Service, you agree to the terms of this Agreement on behalf of your child. You are responsible for monitoring and supervising your child's use of the ArtBot Service. If your child is using the ArtBot Service and is either under 13 or does not have your permission, please contact us immediately so that we can disable his or her access.</p><p>WARNING: Even if you are old enough to use the ArtBot Service and/or have your parent's or guardian's permission, some of the content available within the ArtBot Service may not be appropriate for you. Some content may contain "R-rated" material, nudity, profanity, and mature subject matter. If you are under 18, do not view such content, and seek your parent’s permission when you are unsure if content is appropriate for you.</p><p>2. License to Use the ArtBot Service
LICENSE: ArtBot gives you a personal, worldwide, royalty-free, non-commercial, non-assignable and non-exclusive license to use the software. This includes the right to access content available through the ArtBot Service.</p><p>You may use our Services for limited commercial use, such as uploading original content to the ArtBot platform or any other use that ArtBot specifically addresses in writing.</p><p>RESTRICTIONS: Except as expressly permitted by ArtBot in writing, you will not reproduce, redistribute, sell, create derivative works from, decompile, reverse engineer, or disassemble the ArtBot Service. Nor will you take any measures to interfere with or damage the ArtBot Service. All rights not expressly granted by ArtBot are reserved.</p><p>3. Privacy
Your privacy rights are set forth in our Privacy Policy, which forms a part of this Agreement. We will NEVER sell or share any of your personal information without your express consent. Please review the Privacy Policy to learn about what kind of personal data we use and how we protect it.</p><p>4. Membership
REGISTRATION: To fully use the ArtBot Service, you must register as a member by providing a user name, password, and valid email address. You must provide complete and accurate registration information to ArtBot and notify us if your information changes. If you are a business, government, or non-profit entity, the person whose email address is associated with the account must have the authority to bind the entity to this Agreement.</p><p>USER NAME: We encourage you to use your real name. If you are a business, government, or non-profit entity, you must use the actual name of your organization. You may not use someone else's name, a name that violates any third party right, or a name that is obscene or otherwise objectionable.</p><p>ACCOUNT SECURITY: You are responsible for all activity that occurs under your account, including any activity by unauthorized users. You must not allow others to use your account. You must safeguard the confidentiality of your password. If you are using a computer that others have access to, you must log out of your account after using the ArtBot Service. If you become aware of an unauthorized access to your account, you must change your password and notify us immediately.</p><p>5. Payments
This section will be expanded upon when we implement monetization features. Stay tuned for further announcements.</p><p>6. Term and Termination; Account Deletion
TERM: This Agreement begins on the date you first use the ArtBot Service and continues as long as you have an account with us.</p><p>ACCOUNT TERMINATION: ArtBot may suspend, disable, or delete your account (or any part thereof) or block or remove any content you submitted if ArtBot determines that you have violated any provision of this Agreement or that your conduct or content would tend to damage ArtBot's reputation and goodwill. If ArtBot deletes your account for the foregoing reasons, you may not re-register for the ArtBot Service. ArtBot may block your email address and Internet protocol address to prevent further registration. ArtBot may also delete your account if your account is inactive for twelve (12) months or longer.</p><p>EFFECT OF TERMINATION/ACCOUNT DELETION: Upon termination, all licenses granted by ArtBot will terminate. Sections 6 and 11 through 16 shall survive termination. In the event of account deletion for any reason, content that you submitted, and account balances may no longer be available. ArtBot shall not be responsible for the loss of such content or money.</p><p>7. Content Restrictions
You may not upload, post, or transmit (collectively, "submit") any video, image, text, audio recording, or other work (collectively, "content") that:</p><p>Infringes any third party's copyrights or other rights (e.g., trademark, privacy rights, etc.);
Contains pornography;
Contains hateful, defamatory, or discriminatory content or incites hatred against any individual or group;
Exploits minors;
Depicts unlawful acts or extreme violence;
Depicts animal cruelty or extreme violence towards animals;
Promotes fraudulent schemes, multi level marketing (MLM) schemes, get rich quick schemes, online gaming and gambling, cash gifting, work from home businesses, or any other dubious money-making ventures; or
Violates any law.</p><p>8. Code of Conduct
In using the ArtBot Service, you must behave in a civil and respectful manner at all times. Further, you will not:</p><p>Act in a deceptive manner by, among other things, impersonating any person;
Harass or stalk any other person;
Harm or exploit minors;
Distribute "spam"; or
Collect information about others
</p><p>ArtBot has the right, but not the obligation, to monitor all conduct on and content submitted to the ArtBot Service.</p><p>9. Licenses Granted by You
You promise you own the content you submit to ArtBot, or you at least have explicit permission to submit content that you do not own from the owner of the content.</p><p>LICENSE TO ARTBOT: As between you and ArtBot, you own the video and audio content that you submit to the ArtBot Service. By submitting content, you grant ArtBot and its affiliates a limited, worldwide, non-exclusive, royalty-free license and right to copy, transmit, distribute, publicly perform and display (through all media now known or hereafter created), and make derivative works from your content for the purpose of (i) displaying the content within the ArtBot Service; (ii) displaying the content on third party websites and applications through a video and/or audio embed or ArtBot's API subject to your content privacy choices; (iii) allowing other users to play, download, and embed on third party websites the content, subject to your content privacy choices; (iii) promoting the ArtBot Service, provided that you have made the content publicly available; and (iv) archiving or preserving the content for disputes, legal proceedings, or investigations.</p><p>LICENSE TO OTHER USERS: You further grant all users of the ArtBot Service permission to view your content for their personal, non-commercial purposes. This includes the right to copy and make derivative works from the content solely to the extent necessary to view the content. The foregoing licenses are in addition to any license you may decide to grant (e.g., a Creative Commons license).</p><p>DURATION OF LICENSES: The above licenses will continue unless and until you remove your content from the ArtBot Service, in which case the licenses will terminate within a commercially reasonable period of time. Notwithstanding the foregoing, the license for legal archival/preservation purposes will continue indefinitely. Please note that removed content may be cached in search engine indices after removal and that ArtBot has no control over such caching.</p><p>9.1 Non-media Content
As between you and ArtBot, you own all non-media content that you submit to the ArtBot Service. You grant ArtBot and its affiliates a worldwide, perpetual, irrevocable, non-exclusive, royalty-free license and right to copy, transmit, distribute, publicly perform and display (through all media now known or hereafter created), and make derivative works from your non-media content. In addition, you waive any so-called "moral rights" in your non-media content. You further grant all users of the ArtBot Service permission to view your non-media content for their personal, non-commercial purposes. If you make suggestions to ArtBot on improving or adding new features to the ArtBot Service, ArtBot shall have the right to use your suggestions without any compensation to you.</p><p>10. Indemnification
If you do something through ArtBot that results in a lawsuit against us, you must help defend us against the lawsuit.

You will indemnify, defend, and hold harmless ArtBot and its affiliates, directors, officers, employees, and agents, from and against all third party actions that: (i) arise from your activities on the ArtBot Service; (ii) assert a violation by you of any term of this Agreement; or (iii) assert that any content you submitted to ArtBot violates any law or infringes any third party right, including any intellectual property or privacy right.</p><p>11. Third Party Copyrights and Other Rights
ArtBot respects the intellectual property rights of others. If you believe that your copyright has been infringed, please send us notice.</p><p>12. Disclaimers
ArtBot reserves the right to modify the ArtBot Service. You are responsible for providing your own access (e.g., computer, mobile device, Internet connection, etc.) to the ArtBot Service. ArtBot has no obligation to screen or monitor any content and does not guarantee that any content available on the ArtBot Service complies with this Agreement or is suitable for all users. ArtBot provides the ArtBot Service on an "as is" and "as available" basis. You therefore use the ArtBot Service at your own risk. ArtBot expressly disclaims any and all warranties of any kind, whether express or implied, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose, non-infringement, and any other warranty that might arise under any law. Without limiting the foregoing, ArtBot makes no representations or warranties: That the ArtBot Service will be permitted in your jurisdiction; That the ArtBot Service will be uninterrupted or error-free; Concerning any content submitted by any member; Concerning any third party's use of content that you submit; That any content you submit will be made available on the ArtBot Service or will be stored by ArtBot; That the ArtBot Service will meet your business or professional needs; That ArtBot will continue to support any particular feature of the ArtBot Service; or Concerning sites and resources outside of the ArtBot Service, even if linked to from the ArtBot Service. To the extent any disclaimer or limitation of liability does not apply, all applicable express, implied, and statutory warranties will be limited in duration to a period of thirty (30) days after the date on which you first used the ArtBot Service, and no warranties shall apply after such period.</p><p>13. Limitation of Liability
To the fullest extent permitted by law: (i) ArtBot shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to damages for loss of profits, goodwill, use, data or other intangible losses; and (ii) ArtBot's total liability to you shall not exceed the amounts paid by you to ArtBot over the twelve (12) months preceding your claim(s).</p><p>14. Compliance Notice Pursuant to 18 U.S.C. § 2257
All pictures, graphics, videos, audio, and other media displayed on the ArtBot Service are exempt from 18 U.S.C. § 2257 and 28 C.F.R. 75 because they do not consist of depictions of conduct as specifically listed in 18 U.S.C. § 2256 (2) (A) - (D), but are merely, at most, depictions of non-sexually explicit nudity, or are depictions of simulated sexual conduct, or are otherwise exempt because the visual depictions were created prior to July 3, 1995. ArtBot is not the primary producer of content contained in the ArtBot Service.</p><p>15. General Provisions
GOVERNING LAW: This Agreement shall be governed by the laws of the State of Indiana, United States of America, without regard to principles of conflicts of law. The Uniform Commercial Code, the Uniform Computer Information Transaction Act, and the United Nations Convention of Controls for International Sale of Goods shall not apply.</p><p>DISPUTES: Any action arising out of or relating to this Agreement or your use of the ArtBot Service must be commenced in the state or federal courts located in Hamilton County, Indiana, United States of America (and you consent to the jurisdiction of those courts). In any such action, ArtBot and you irrevocably waive any right to a trial by jury.</p><p>INTERPRETATION; SEVERABILITY; WAIVER; REMEDIES: Headings are for convenience only and shall not be used to construe the terms of this Agreement. If any term of this Agreement is found invalid or unenforceable by any court of competent jurisdiction, that term will be severed from this Agreement. No failure or delay by ArtBot in exercising any right hereunder will waive any further exercise of that right. ArtBot's rights and remedies hereunder are cumulative and not exclusive.</p><p>SUCCESSORS</p><p>ASSIGNMENT; NO THIRD PARTY BENEFICIARIES: This Agreement is binding upon and shall inure to the benefit of both parties and their respective successors, heirs, executors, administrators, personal representatives, and permitted assigns. You may not assign this Agreement without ArtBot's prior written consent. No third party shall have any rights hereunder.</p><p>NOTICES: You consent to receive all communications including notices, agreements, disclosures, or other information from ArtBot electronically. ArtBot may provide all such communications by email or by posting them on the ArtBot Service.</p><p>Nothing herein shall limit ArtBot's right to object to subpoenas, claims, or other demands.</p><p>MODIFICATION: This Agreement may not be modified except by a revised Terms of Service posted by ArtBot on the ArtBot Site or a written amendment signed by an authorized representative of ArtBot.</p><p>This Agreement constitutes the entire understanding between ArtBot and you concerning the subject matter hereof and supersedes all prior agreements and understandings regarding the same.</p><h5>Contact Information</h5><p>
If you have any questions about these Terms or the Services, please contact us at support@artbot.tv.</p>`
};
export const contact = {
    title: 'Contact ',
    desc: 'Email: support@artbot.tv\nReddit: https://www.reddit.com/r/ArtBot'
};
export const privacy = {
    title: 'Privacy Policy',
    desc: `<div style="user-select:none;"><h5>Last updated August 31, 2018</h5><p>Thank you for choosing to be part of our community at Artbot, LLC (“Company ”, “we”, “us”, or “our”). We are committed to protecting your personal information and your right to privacy. If you have any questions or concerns about our policy, or our practices with regards to your personal information, please contact us at support@artbot.tv.</p>
	<p>When you visit our website https://artbot.tv, and use our services, you trust us with your personal information. We take your privacy very seriously. In this privacy notice, we describe our privacy policy. We seek to explain to you in the clearest way possible what information we collect, how we use it and what rights you have in relation to it. We hope you take some time to read through it carefully, as it is important. If there are any terms in this privacy policy that you do not agree with, please discontinue use of our Sites and our services.</p>
	<p>This privacy policy applies to all information collected through our website (such as https://artbot.tv), and/or any related services, sales, marketing or events (we refer to them collectively in this privacy policy as the "Sites"). 
Please read this privacy policy carefully as it will help you make informed decisions about sharing your personal information with us.  </p>
<h4>1. WHAT INFORMATION DO WE COLLECT?  </h4> <h6>Personal information you disclose to us </h6>	<p>In Short: We collect personal information that you provide to us such as name, address, contact information, passwords and security data, and payment information . </p>
<p>We collect personal information that you voluntarily provide to us when registering at the Sites expressing an interest in obtaining information about us or our products and services, when participating in activities on the Sites (such as posting messages in our online forums or entering competitions, contests or giveaways) or otherwise contacting us .</p>
<p>The personal information that we collect depends on the context of your interactions with us and the Sites , the choices you make and the products and features you use. The personal information we collect can include the following:</p>
<p>Name and Contact Data. We collect your first and last name, email address, postal address, phone number, and other similar contact data.</p>
<p>Credentials. We collect passwords, password hints, and similar security information used for authentication and account access.</p>
<p>Payment Data. We collect data necessary to process your payment if you make purchases, such as your payment instrument number (such as a credit card number), and the security code associated with your payment instrument. All payment data is stored by our payment processor and you should review its privacy policies and contact the payment processor directly to respond to your questions.</p>
<p>All personal information that you provide to us must be true, complete and accurate, and you must notify us of any changes to such personal information.  </p>
<h5>Information automatically collected </h5><p>In Short: Some information – such as IP address and/or browser and device characteristics – is collected automatically when you visit our Sites .</p>
<p>We automatically collect certain information when you visit, use or navigate the Sites . This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Sites and other technical information. This information is primarily needed to maintain the security and operation of our Sites , and for our internal analytics and reporting purposes.</p>
<p>Like many businesses, we also collect information through cookies and similar technologies.</p>
<h5>Information collected from other sources </h5><p>In Short:  We may collect limited data from public databases, marketing partners, and other outside sources.  </p>
<p>We may obtain information about you from other sources, such as public databases, joint marketing partners, as well as from other third parties. Examples of the information we receive from other sources include: social media profile information; marketing leads and search results and links, including paid listings (such as sponsored links).</p>
<h4>2. HOW DO WE USE YOUR INFORMATION? </h4><p>In Short:  We process your information for purposes based on legitimate business interests, the fulfillment of our contract with you, compliance with our legal obligations, and/or your consent.  </p>
<p>We use personal information collected via our Sites for a variety of business purposes described below. We process your personal information for these purposes in reliance on our legitimate business interests, in order to enter into or perform a contract with you, with your consent, and/or for compliance with our legal obligations. We indicate the specific processing grounds we rely on next to each purpose listed below.   </p>
<p>We use the information we collect or receive: </p><p>To facilitate account creation and logon process. If you choose to link your account with us to a third party account *(such as your Google or Facebook account), we use the information you allowed us to collect from those third parties to facilitate account creation and logon process.  </p>
<p>To send you marketing and promotional communications. We and/or our third party marketing partners may use the personal information you send to us for our marketing purposes, if this is in accordance with your marketing preferences. You can opt-out of our marketing emails at any time (see the " WHAT ARE YOUR PRIVACY RIGHTS " below). </p>
<p>To send you marketing and promotional communications. We and/or our third party marketing partners may use the personal information you send to us for our marketing purposes, if this is in accordance with your marketing preferences. You can opt-out of our marketing emails at any time (see the " WHAT ARE YOUR PRIVACY RIGHTS " below). </p>
<p>Fulfill and manage your orders. We may use your information to fulfill and manage your orders, payments, returns, and exchanges made through the Sites .   </p>
<p>To post testimonials. We post testimonials on our Sites that may contain personal information. Prior to posting a testimonial, we will obtain your consent to use your name and testimonial. If you wish to update, or delete your testimonial, please contact us at support@artbot.tv and be sure to include your name, testimonial location, and contact information. </p>
<p>Deliver targeted advertising to you. We may use your information to develop and display content and advertising (and work with third parties who do so) tailored to your interests and/or location and to measure its effectiveness. </p>
<p>Administer prize draws and competitions. We may use your information to administer prize draws and competitions when you elect to participate in competitions.  </p>
<p>Request Feedback. We may use your information to request feedback and to contact you about your use of our Sites .  </p>
<p>To protect our Sites. We may use your information as part of our efforts to keep our Sites safe and secure (for example, for fraud monitoring and prevention). </p>
<p>To enable user-to-user communications. We may use your information in order to enable user-to-user communications with each user's consent.  </p>
<p>To enforce our terms, conditions and policies. </p><p>To respond to legal requests and prevent harm. If we receive a subpoena or other legal request, we may need to inspect the data we hold to determine how to respond.</p>
<p>For other Business Purposes. We may use your information for other Business Purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Sites , products, services, marketing and your experience.   </p>
<h4>3. WILL YOUR INFORMATION BE SHARED WITH ANYONE? </h4><p>In Short:  We only share information with your consent, to comply with laws, to protect your rights, or to fulfill business obligations.  </p>
<p>We may process or share data based on the following legal basis:
Consent: We may process your data if you have given us specific consent to use your personal information in a specific purpose. </p>
<p>Legitimate Interests: We may process your data when it is reasonably necessary to achieve our legitimate business interests. </p>
<p>Performance of a Contract: Where we have entered into a contract with you, we may process your personal information to fulfill the terms of our contract.</p>
<p>Legal Obligations: We may disclose your information where we are legally required to do so in order to comply with applicable law, governmental requests, a judicial proceeding, court order, or legal process, such as in response to a court order or a subpoena (including in response to public authorities to meet national security or law enforcement requirements).</p>
<p>Vital Interests: We may disclose your information where we believe it is necessary to investigate, prevent, or take action regarding potential violations of our policies, suspected fraud, situations involving potential threats to the safety of any person and illegal activities, or as evidence in litigation in which we are involved.
More specifically, we may need to process your data or share your personal information in the following situations:  </p><p>Vendors, Consultants and Other Third-Party Service Providers. We may share your data with third party vendors, service providers, contractors or agents who perform services for us or on our behalf and require access to such information to do that work. Examples include: payment processing, data analysis, email delivery, hosting services, customer service and marketing efforts. We may allow selected third parties to use tracking technology on the Sites , which will enable them to collect data about how you interact with the Sites over time. This information may be used to, among other things, analyze and track data, determine the popularity of certain content and better understand online activity. Unless described in this Policy, we do not share, sell, rent or trade any of your information with third parties for their promotional purposes. </p>
<p>Business Transfers. We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.  
</p><p>Third-Party Advertisers. We may use third-party advertising companies to serve ads when you visit the Sites . These companies may use information about your visits to our Website(s) and other websites that are contained in web cookies and other tracking technologies in order to provide advertisements about goods and services of interest to you.</p>
<p>Affiliates. We may share your information with our affiliates, in which case we will require those affiliates to honor this privacy policy. Affiliates include our parent company and any subsidiaries, joint venture partners or other companies that we control or that are under common control with us.</p>
<p>Business Partners. We may share your information with our business partners to offer you certain products, services or promotions.  </p>
<h4>4. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?  </h4>
<p>In Short:  We may use cookies and other tracking technologies to collect and store your information.  </p>
<p>We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Policy.  </p>
<h4>5. IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY?  </h4>
<p>n Short:  We may transfer, store, and process your information in countries other than your own.  </p>
<p>Our servers are located in United States . If you are accessing our Sites from outside United States , please be aware that your information may be transferred to, stored, and processed by us in our facilities and by those third parties with whom we may share your personal information (see "  WILL YOUR INFORMATION BE SHARED WITH ANYONE? " above), in United States, and other countries.  </p>
<p>If you are a resident in the European Economic Area, then these countries may not have data protection or other laws as comprehensive as those in your country. We will however take all necessary measures to protect your personal information in accordance with this privacy policy and applicable law.  </p>
<p>EU-U.S. Privacy Shield Framework:  </p><p>In particular Company complies with the EU-U.S. Privacy Shield Framework as set forth by the U.S. Department of Commerce regarding the collection, use, and retention of personal information transferred from the European Union to the United States and has certified its compliance with it. As such, Company is committed to subjecting all personal information received from European Union (EU) member countries, in reliance on the Privacy Shield Framework, to the Framework’s applicable Principles. To learn more about the Privacy Shield Framework, visit the U.S. Department of Commerce’s Privacy Shield List.</p>
<p>Company is responsible for the processing of personal information it receives, under the Privacy Shield Framework, and subsequently transfers to a third party acting as an agent on its behalf. </p>
<p>With respect to personal information received or transferred pursuant to the Privacy Shield Framework, Company is subject to the regulatory enforcement powers of the U.S. FTC. In certain situations, we may be required to disclose personal information in response to lawful requests by public authorities, including to meet national security or law enforcement requirements.</p>
<h4>6. WHAT IS OUR STANCE ON THIRD-PARTY WEBSITES?  </h4>
<p>In Short:  We are not responsible for the safety of any information that you share with third-party providers who advertise, but are not affiliated with, our websites.  </p>
<p>The Sites may contain advertisements from third parties that are not affiliated with us and which may link to other websites, online services or mobile applications. We cannot guarantee the safety and privacy of data you provide to any third parties. Any data collected by third parties is not covered by this privacy policy. We are not responsible for the content or privacy and security practices and policies of any third parties, including other websites, services or applications that may be linked to or from the Sites . You should review the policies of such third parties and contact them directly to respond to your questions.</p>
<h4>7. HOW LONG DO WE KEEP YOUR INFORMATION? </h4>
<p>In Short:  We keep your information for as long as necessary to fulfill the purposes outlined in this privacy policy unless otherwise required by law. </p>
<p>We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy policy, unless a longer retention period is required or permitted by law (such as tax, accounting or other legal requirements). No purpose in this policy will require us keeping your personal information for longer than 2 years past the termination of the user's account .  </p>
<p>When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize it, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.</p>
<h4>8. HOW DO WE KEEP YOUR INFORMATION SAFE?   </h4>
<p>In Short:  We aim to protect your personal information through a system of organizational and technical security measures. </p>
<p>We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, please also remember that we cannot guarantee that the internet itself is 100% secure. Although we will do our best to protect your personal information, transmission of personal information to and from our Sites is at your own risk. You should only access the services within a secure environment. </p>
<h4>9. DO WE COLLECT INFORMATION FROM MINORS?  </h4>
<p>In Short:  We do not knowingly collect data from or market to children under 18 years of age.</p>
<p>We do not knowingly solicit data from or market to children under 18 years of age. By using the Sites , you represent that you are at least 18 or that you are the parent or guardian of such a minor and consent to such minor dependent’s use of the Sites . If we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records. If you become aware of any data we have collected from children under age 18, please contact us at support@artbot.tv . </p>
<h4>10. WHAT ARE YOUR PRIVACY RIGHTS?  </h4><p>In Short:   In some regions, such as the European Economic Area, you have rights that allow you greater access to and control over your personal information. You may review, change, or terminate your account at any time.  </p>
<p>In some regions (like the European Economic Area), you have certain rights under applicable data protection laws. These may include the right (i) to request access and obtain a copy of your personal information, (ii) to request rectification or erasure; (iii) to restrict the processing of your personal information; and (iv) if applicable, to data portability. In certain circumstances, you may also have the right to object to the processing of your personal information. To make such a request, please use the contact details  provided below. We will consider and act upon any request in accordance with applicable data protection laws. </p>
<p>If we are relying on your consent to process your personal information, you have the right to withdraw your consent at any time. Please note however that this will not affect the lawfulness of the processing before its withdrawal.   </p>
<p>If you are resident in the European Economic Area and you believe we are unlawfully processing your personal information, you also have the right to complain to your local data protection supervisory authority. You can find their contact details here: <a target="_blank" href="https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm">https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm</a>  </p>
<h4>Account Information  </h4>
<p>If you would at any time like to review or change the information in your account or terminate your account, you can:  

■   Log into your account settings and update your user account. </p>
<p>Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, some information may be retained in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our Terms of Use and/or comply with legal requirements.</p>
<p>Cookies and similar technologies: Most Web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove cookies and to reject cookies. If you choose to remove cookies or reject cookies, this could affect certain features or services of our Sites . To opt-out of interest-based advertising by advertisers on our Sites   visit   https://www.aboutads.info/choices/ .</p>
<p>Opting out of email marketing: You can unsubscribe from our marketing email list at any time by clicking on the unsubscribe link in the emails that we send or by contacting us using the details provided below. You will then be removed from the marketing email list – however, we will still need to send you service-related emails that are necessary for the administration and use of your account. To otherwise opt-out, you may: ■   Access your account settings and update preferences.   </p>
<h4>11. CONTROLS FOR DO-NOT-TRACK FEATURES </h4>
<p>Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track (“DNT”) feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. No uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this Privacy Policy. </p>
<h4>12. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?  </h4>
<p>In Short:  Yes, if you are a resident of California, you are granted specific rights regarding access to your personal information.   </p>
<p>California Civil Code Section 1798.83, also known as the “Shine The Light” law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below. </p>
<p>If you are under 18 years of age, reside in California, and have a registered account with the Sites , you have the right to request removal of unwanted data that you publicly post on the Sites . To request removal of such data, please contact us using the contact information provided below, and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the Sites , but please be aware that the data may not be completely or comprehensively removed from our systems.</p>
<h4>13. DO WE MAKE UPDATES TO THIS POLICY?  </h4><p>In Short:  Yes, we will update this policy as necessary to stay compliant with relevant laws.  </p>
<p>We may update this privacy policy from time to time. The updated version will be indicated by an updated “Revised” date and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy policy, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy policy frequently to be informed of how we are protecting your information. </p>
<h4>14. HOW CAN YOU CONTACT US ABOUT THIS POLICY?  </h4>
<p>If you have questions or comments about this policy, you may email us at support@artbot.tv or by post to:</p>
<p > Artbot, LLC</p>    
<p > &nbsp;United States</p></div>
`
};
